---
title: LIFFT Cashew Project
collections:
  posts:
    title: Posts
    output: true
  preleases:
    title: Preleases
    output: true
  publications:
    title: Publications
    output: true
  events:
    title: Events
    output: true
  stories:
    title: Stories
    output: true
  teams:
    title: Teams
    output: true
  faqs:
    title: faqs
    output: true
  jobs:
    title: jobs
    output: true
  donors:
    title: donors
    output: true
  indicators:
    title: indicators
    output: true
email: lifftcashewinfo@shelter.org
tel1: "(+221) 33 991 94 55"
tel2: "+ 221 33 823 44 45"
telgb: "(+245) 95 663 74 13"
telgm: "(+220) 353 53 86"
sn_address: 178 Nema Complementaire, Ziguinchor
gb_address: Rua Lamine Indjai na Cidade de Bissau
gm_address: Kotu East, KMC, The Gambia
logo_white: "/assets/img/logo_white_2.png"
logo_white2: "/assets/img/logo_white2.png"
logo_dark: "/assets/images/logo_dark.png"
logo_new: "/assets/img/logo_new.png"
logo_colored: "/assets/img/lifft_logo_color.png"
logo_blanc: "/assets/img/lifft_logo_white.png"
description: Our program develops value chain linkages necessary to support an integrated
  regional trade network for the cashew value chain,  and enhancing the production
  and trade of cashews in local and international markets.
copyright_text: Copyright &copy;2020 Shelter For Life International. All Rights Reserved
facebook: https://web.facebook.com/LIFFTCashewSFL/
twitter: https://twitter.com/LIFFTCashew
linkedin: https://www.linkedin.com/company/lifft-cashew-project/
baseurl: ''
url: ''
twitter_username: LIFFTCashew
github_username: jekyll
plugins:
- jekyll-feed
- jekyll-menus
