---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: _config.yml
  label: config
- type: heading
  label: MODIFY THE MAIN PAGES
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: WHAT WE DO
- type: directory
  path: _teams
  label: Teams
  create: all
  match: "**/*"
  templates:
  - team
- type: directory
  path: _donors
  label: Donors
  create: all
  match: "**/*"
  templates:
  - donor
- type: directory
  path: _faqs
  label: Faqs
  create: all
  match: "**/*"
  templates:
  - faq
- type: heading
  label: IMPACT
- type: directory
  path: _indicators
  label: Indicators
  create: all
  match: "**/*"
  templates:
  - indicator
- type: directory
  path: _stories
  label: Stories
  create: all
  match: "**/*"
  templates:
  - story
- type: heading
  label: NEWS AND EVENTS
- type: jekyll-posts
  label: Blog Posts
  create: all
  templates:
  - post
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: directory
  path: _preleases
  label: Press releases
  create: all
  match: "**/*"
  templates:
  - press
- type: directory
  path: _publications
  label: Publications
  create: all
  match: "**/*"
  templates:
  - publication
- type: heading
  label: GET INVOLVED
- type: directory
  path: _jobs
  label: Jobs
  create: all
  match: "**/*"
  templates:
  - job
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
